/*
How many direct and indirect child nodes does each parent node — starting with the element with an id of 1 —
have in the DOM generated by the following HTML:

<div id="1">
  <h1 id="2">Hello, <em id="3">World</em></h1>
  <p id="4">
    Welcome to wonderland. This is an
    <span id="5">awesome</span> place.
  </p>
  <a href="#" id="6"><strong id="7">Enter</strong></a>
  <div id="8"><p id="9"><a href="#" id="10">Go back</a></p></div>
</div>

Consider the following when counting the direct and indirect child nodes for each parent node:
  Any DOM node that has at least one child node is a parent node.
  Indirect child nodes are all descendants of a node's direct children, excluding the direct children themselves.
*/

/*
ID 1:
  Direct children (9):
    Empty node between id 1 and 2
    id 2 (h1)
    Empty node between id 2 and 4
    id 4 (p)
    Empty node between id 4 and 6
    id 6 (a)
    Empty node between id 6 and 8
    id 8 (div)
    Empty node after id 8

  Indirect children (12):
    Text node inside id 2 ("Hello, ")
    id 3 (em)
    Text node inside id 3 ("World")
    Text node 1 inside id 4 (whitespace + "Welcome to wonderingland. This is an" + whitespace)
    id 5 (span)
    Text node inside id 5 ("awesome")
    Text node 2 inside id 4 (" place." + whitespace)
    id 7 (strong)
    Text node inside id 7 ("Enter")
    id 9 (p)
    id 10 (a)
    Text node inside id 10 ("Go back")

ID 2:
  Direct children (2):
    Text node inside id 2 ("Hello, ")
    id 3 (em)

  Indirect children (1):
    Text node inside id 3 ("World")

ID 3:
  Direct children (1):
    Text node inside id 3 ("World")

  Indirect children (0):
    None

ID 4:
  Direct children (3):
    Text node 1 inside id 4 (whitespace + "Welcome to wonderingland. This is an" + whitespace)
    id 5 (span)
    Text node 2 inside id 4 (" place." + whitespace)

  Indirect children (1):
    Text node inside id 5 ("awesome")

ID 5:
  Direct children (1):
    Text node inside id 5 ("awesome")

  Indirect children (0):
    None

ID 6:
  Direct children (1):
    id 7 (strong)

  Indirect children (1):
    Text node inside id 7 ("Enter")

ID 7:
  Direct children (1):
    Text node inside id 7 ("Enter")

  Indirect children (0):
    None

ID 8:
  Direct children (1):
    id 9 (p)

  Indirect children (2):
    id 10 (a)
    Text node inside id 10 ("Go back")

ID 9:
  Direct children (1):
    id 10 (a)

  Indirect children (1):
    Text node inside id 10 ("Go back")

ID 10:
  Direct children (1):
    Text node inside id 10 ("Go back")

  Indirect children (0):
    None
*/

/*
Write code that returns the number of direct and indirect child nodes for a given parent node as an array.

(I tested this by using child_nodes.html and pasting the JS below into the console, then calling the function. It worked!)
*/

function getAllChildCount(node) {
  let childCount = 0;
  let children = node.childNodes;
  for (let child of children) {
    childCount += 1 + getAllChildCount(child);
  }
  return childCount;
}

function childNodes(nodeId) {
  let children = document.getElementById(nodeId).childNodes;

  let indirectChildrenCount = 0;
  for (let child of children) {
    indirectChildrenCount += getAllChildCount(child);
  }

  return [children.length, indirectChildrenCount];
}


// sample output
// > childNodes(1);
// = [9, 12]
// > childNodes(4);
// = [3, 1]
// > childNodes(9);
// = [1, 1]